"""Added banned field

Revision ID: 0f5b415f2308
Revises: 497267669870
Create Date: 2018-04-21 00:56:27.907961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5b415f2308'
down_revision = '497267669870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_banned')
    # ### end Alembic commands ###
